name: Python application workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Set this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List all files
      run: ls -R

    - name: Run Pytest with verbosity
      run: pytest -vv

    - name: Log in to DockerHub
      if: success() # This ensures the step only runs if the tests pass
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: success() # This ensures the step only runs if the tests pass
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: srujit12091997/devops_demo:latest
